name: 'Yasuharu Yanamura'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    required: true
    description: 'GitHub token(require pull request write permission. dont use GITHUB_TOKEN)'
runs:
  using: 'node12'
  main: 'dist/index.js'
