name: 'test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'
  schedule:
    - cron: '0 23 * * *'

jobs:
  test:
    env:
      TZ: 'Asia/Tokyo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          trigger_title: "[->Ready]"
